# -*- coding: utf-8 -*-
"""INST414-InClassE.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NEymgjmqpiAYY90QVZX2inxc7zPoD24r
"""

import json
loop_counter = 0
result_count = 0
with open("/content/imdb_movies_1985to2022.json", "r") as in_file:
    for line in in_file:
        print(line)
        this_movie = json.loads(line)
        #break prevents the rest of movies from printing
        actors = this_movie["actors"]
        ratings = this_movie["rating"]

        for actor in actors:
          actor_name = actor[1]
          print("\t", actor_name)
          if actor_name == "Hugh Jackman":
            for rating in ratings:
              rating_list = rating

        loop_counter += 1

        if loop_counter > 5:
          break

this_movie

my_list = list(this_movie.values())